# Site
repository: beyonditpl/beyonditpl.github.io
favicon: images/favicon.ico

# Personal info
name: Kamil Jarocha
title: Senior Cloud Architect / DevSecOps
email: kamil.jarocha@gmail.com
website: www.github.com/beyonditpl

# Social links
#twitter_username: beyondit
github_username:  beyonditpl
# dribbble_username: jekyll
facebook_username: hejzehejhejzeho
# flickr_username: jekyll
instagram_username: kamiljarocha
linkedin_username: beyond-it-kj
# pinterest_username: jekyll
youtube_username: kamil.jarocha@gmail.com
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
cert_image_aws_devops: images/AWS-DevOpsEngineer-Professional.png
cert_image_aws_sysops: images/AWS-SysOpAdmin-Associate.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Kamil and I'm a senior cloud architect and DevSecOps. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: beyonditpl/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

darkmode: true
